# Generated by Django 3.1.5 on 2021-01-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=16822, primary_key=True, serialize=False),
        ),
    ]
