# Generated by Django 3.1.5 on 2021-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_auto_20210124_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=11257, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
