# Generated by Django 3.1.5 on 2021-01-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0003_auto_20210124_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('views', models.IntegerField(auto_created=True, default=0, editable=False)),
                ('clicks', models.IntegerField(auto_created=True, default=0, editable=False)),
                ('id', models.IntegerField(default=12197, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('imgUrl', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='clicks',
            field=models.IntegerField(auto_created=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=10797, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='views',
            field=models.IntegerField(auto_created=True, default=0, editable=False),
        ),
    ]
