# Generated by Django 3.1.5 on 2021-01-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_auto_20210124_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='advertiser',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.IntegerField(default=11635, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=18831, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
