# Generated by Django 3.1.5 on 2021-01-24 21:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0005_auto_20210125_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='ads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], editable=False, size=None),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.IntegerField(default=13433, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=17216, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
