# Generated by Django 3.1.5 on 2021-01-25 07:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_auto_20210125_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='ads',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='adsId',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, editable=False, size=None),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.IntegerField(default=19684, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=19542, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
