# Generated by Django 3.1.5 on 2021-01-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0007_auto_20210125_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.IntegerField(default=12585, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=17098, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
