# Generated by Django 3.1.5 on 2021-01-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0008_auto_20210125_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.advertiser'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.IntegerField(default=12870, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=18812, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
