# Generated by Django 3.1.5 on 2021-01-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0009_auto_20210125_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='adsId',
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.IntegerField(default=13693, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=13138, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
