# Generated by Django 3.1.5 on 2021-01-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0010_auto_20210125_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.IntegerField(default=17365, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=10983, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
