# Generated by Django 3.1.5 on 2021-01-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0012_auto_20210125_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.IntegerField(default=10523, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=15881, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
